name: yellowstone-editorial
favicon: null
layout_spectrum: 0.75667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19292c'
    - '#374347'
    - '#787f79'
    - '#99988c'
    - '#c8c3b0'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
